
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: self-hosted
    environment: production
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    # Build
    - name: Build Docker image
      run: docker build -t jinkim1004/docker-react -f Dockerfile.dev . 
    # S3
    - name: Upload docker image to S3
      run:  aws s3 cp jinkim1004/docker-react s3://elasticbeanstalk-us-east-1-473365992405/docker-react
   
