
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: self-hosted
    environment: production
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    # Build
    - name: Build Docker image
      run: sudo docker build -t jinkim1004/docker-react:latest . 
    - name: Docker Image to Zip
      run: sudo docker save jinkim1004/docker-react:latest > docker-react.zip    # Docker Login
    #- name: Docker login
    #  run:  echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin    # Docker push
    - name: S3
      run:  aws s3 cp docker-react.zip  s3://elasticbeanstalk-us-east-1-473365992405/docker-react.zip
   
