
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      run: docker build -t jinkim1004/docker-react -f Dockerfile.dev . 
      run: docker run jinkim1004/docker-react npm run test -- --coverage
